---
# tasks file for webserver
- name: Installeer Apache
  ansible.builtin.package:
    name: apache2
    state: present

- name: Installeer PHP
  ansible.builtin.package:
    name: php
    state: present

- name: Installeer php-mysql
  ansible.builtin.package:
    name: php-mysql
    state: present
